# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillTrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('USER', 'Standard User'), ('ADMIN', 'Administrator')],
                default='USER',
                max_length=10,
            ),
        ),
    ]
